defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6-jessie-node-browsers

version: 2
jobs:

  install:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run: yarn install
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
        - persist_to_workspace:
            root: ~/repo
            paths:
              - ./*

  test:
    <<: *defaults
    steps:
        - attach_workspace:
          at: ~/repo
        - run: yarn test

  build:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - run: yarn generate
        - persist_to_workspace:
            root: ~/repo
            paths:
              - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://dev-ventures-top --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws s3 sync ./dist/ s3://dev-ventures-top --exact-timestamps --delete --exclude "*" --include "*.js" --cache-control max-age=31536000
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  standard-workflow:
    jobs:
      - install:
          filters:
              branches:
                  only:
                      - master
      - test:
          filters:
              branches:
                  only:
                      - master
      - build:
          requires:
              - test
          filters:
              branches:
                  only:
                      - master
